### ISSUE TITLE
The stream has mosaic both in chrome beta and chrome dev

### ISSUE THREAD

**Issue by wayunge** [open-webrtc-toolkit/owt-client-javascript#268]
environment:
mcu: 20191007/Release-v20191007ubuntu.tgz
system: ubuntu software
browser: chrome beta and chrome dev
step:
1 . user join room
2. user publish a stream with any audioCodec and any videoCodec  and subscribe the stream
3.wait a few seconds(No more than five seconds)
result:
there has mosaic both on forward stream and mix steam
expect:
the stream should work well both in chrome beta and chrome dev
additional：
 Test between chrome beta and chrome dev and chrome  many times, there have mosaic on stream only in chrome beta and chrome dev

**Comment by starwarfan** [comment]
Do you have any images?

**Comment by lzl** [comment]
Same issue happens to me. OWT v4.2.1 and Google Chrome for Mac (any recent versions).

When published the stream, I found the upload rate of that stream would be smaller and smaller. That's why "mosaic" happens in the subscription side.

To "resolve mosaic", I have to relaunch my Chrome browser and repeat that pub/sub steps to see if it disappears. If not, I will relaunch browser again until it does. @wayunge could you try this routine and confirm whether we are in the same issue or not?

**Comment by jianjunz** [comment]
Hi @lzl,

Perhaps your issue is different from the one reported here if you observed it in Chrome 77 or earlier. This issue might be caused by incorrect bandwidth estimation. We observed that server side doesn't honor the RTP extension ID for transport-wide congestion control negotiated in SDP. Instead, it hard coded to a fixed value. So the bandwidth estimation in Chrome 78 beta doesn't work properly because the feedback from server is incorrect. It has been fixed by https://github.com/open-webrtc-toolkit/owt-server/pull/296.

@wayunge, could you please verify this issue on a server with above PR applied? If this issue still exists, it may be caused by another reason. Thanks.

**Comment by wayunge** [comment]
Hi @lzl ,hi @jianjunz 
I have verified this issue on a server with above PR applied,Version:20191013/Release-v20191013ubuntu4.2.x.tgz,there have no mosaic on stream in chrome beta(Version 78.0.3904.50) and chrome dev(Version 79.0.3938.0).Google Chrome for Mac (any recent versions) need to be re-validated.
