### ISSUE TITLE
p2p: Multiple video codec publication expectation is wrong

### ISSUE THREAD

**Issue by zhangyihui1** [open-webrtc-toolkit/owt-client-javascript#92]
1: user1(chrome)  connect server with videoCodec vp9
2: user2(chrome) connect server with videoCodec vp8 and vp9
3: user1 and user2 addAllowRemoteId each other
4: user2 publish local stream to user1
5: user1 publish local stream to user2

expect : user1 and user2 send video codec is vp9
actual : user1 send video codec is vp8 ,user2 send video codec is vp9

chrome version 72

**Comment by jianjunz** [comment]
Currently, we set codec and bitrate by modifying SDP. It seems that Chrome still uses VP8 even it is removed between `CreateOffer` and `SetLocalDescription`. However, modifying SDP is not recommended. We're going to use `RTPSender.setParameters` in the future. This issue is expected to be fixed at that time.

**Comment by jianjunz** [comment]
This issue seems to be fixed in the master branch.
